FROM mcr.microsoft.com/dotnet/sdk:10.0

ENV DATA_DIR="/serverdata"
ENV STEAMCMD_DIR="${DATA_DIR}/steamcmd"
ENV BASE_SERVER_DIR="${DATA_DIR}/serverfiles"
ENV INSTANCE_SERVER_DIR="/opt/instance"

ENV LD_LIBRARY_PATH="/opt/instance/game/bin/linuxsteamrt64:"

ENV AUTOLOAD_PLUGINS=true
ENV PLUGINS_DIR="/opt/custom-plugins"

ENV INSTALL_5STACK_PLUGIN=true

ENV GAME_ID="730"
ENV GAME_PARAMS=""
ENV GAME_PORT=27015
ENV VALIDATE=false
ENV USER=steam

ENV STEAM_USER="anonymous"
ENV STEAM_PASSWORD=""

ENV SERVER_ID=""
ENV DEFAULT_MAP="de_inferno"

ENV STEAM_RELAY="false"

ENV SERVER_TYPE="Ranked"

ENV METAMOD_URL=https://mms.alliedmods.net/mmsdrop/2.0/mmsource-2.0.0-git1374-linux.tar.gz
ENV COUNTER_STRIKE_SHARP_URL=https://github.com/roflmuffin/CounterStrikeSharp/releases/download/v1.0.369/counterstrikesharp-with-runtime-linux-1.0.369.zip
ENV CS2FOW_URL=https://github.com/karola3vax/CS2FOW/releases/download/v0.1.1-preview/cs2fow-0.1.1-preview-linux-x86_64.zip
ENV CS2FOW_SHA256=517eff95d5bae15b0aa9fb79c47a6eebe3bb7033228bfe9d7d397fc9446750d6
# prebake pack v0.1.0-preview is upstream-declared compatible with plugin v0.1.1-preview; bump both pins together after checking upstream release notes
ENV CS2FOW_PREBAKE_URL=https://github.com/karola3vax/CS2FOW/releases/download/v0.1.0-preview/cs2fow-0.1.0-preview-official-maps.zip
ENV CS2FOW_PREBAKE_SHA256=66114d74a13f933f38f81a79d2fa10ad89e2cf254b45afc5c589c8782067215c
ENV CS2FOW_PREBAKE_VERSION=0.1.0-preview

RUN apt-get update && \
	apt-get install -y --no-install-recommends \
	wget locales procps jq ca-certificates curl unzip \
	&& rm -rf /var/lib/apt/lists/*

ENV LANG=en_US.UTF-8
ENV LANGUAGE=en_US:en
ENV LC_ALL=en_US.UTF-8

RUN mkdir -p $DATA_DIR $STEAMCMD_DIR $BASE_SERVER_DIR $INSTANCE_SERVER_DIR && \
	useradd -d $DATA_DIR -s /bin/bash $USER && \
	ulimit -n 2048

RUN mkdir -p /opt/metamod /opt/counterstrikesharp && \
	wget -q $METAMOD_URL -O /tmp/metamod.tar.gz && \
	tar -xz -C /opt/metamod -f /tmp/metamod.tar.gz && \
	rm /tmp/metamod.tar.gz && \
	wget -q $COUNTER_STRIKE_SHARP_URL -O /tmp/counterstrikesharp.zip && \
	unzip -q /tmp/counterstrikesharp.zip -d /opt/counterstrikesharp && \
	rm /tmp/counterstrikesharp.zip

RUN mv /opt/metamod/addons /opt/addons && \
	cp -R /opt/counterstrikesharp/addons/metamod /opt/addons && \
	cp -R /opt/counterstrikesharp/addons/counterstrikesharp /opt/addons && \
	mkdir -p /opt/addons/counterstrikesharp/plugins && \
	mkdir -p /opt/dev && \
	rm -rf /opt/metamod /opt/counterstrikesharp

RUN mkdir -p /opt/cs2fow /opt/cs2fow-tools && \
	wget -q $CS2FOW_URL -O /tmp/cs2fow.zip && \
	echo "${CS2FOW_SHA256}  /tmp/cs2fow.zip" | sha256sum -c - && \
	unzip -q /tmp/cs2fow.zip -d /opt/cs2fow && \
	rm /tmp/cs2fow.zip && \
	cp -R /opt/cs2fow/addons/cs2fow /opt/addons && \
	cp /opt/cs2fow/addons/metamod/cs2fow.vdf /opt/addons/metamod/ && \
	cp -R /opt/cs2fow/tools/. /opt/cs2fow-tools/ && \
	rm -rf /opt/cs2fow

WORKDIR /opt/5stack

COPY . .

ENTRYPOINT ["./apps/counterstrikesharp/scripts/dev.sh"]