name: Branch Build and Push

on:
  workflow_dispatch:
    inputs:
      branch_name:
        description: 'Branch name to build from'
        required: true
        type: string

jobs:
  branch-build-push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ github.event.inputs.branch_name || github.ref_name }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build Docker image
      uses: docker/build-push-action@v6
      with:
        context: .
        push: false
        load: true
        tags: mod-builder:latest
        target: zip-creator
        build-args: |
          RELEASE_VERSION=${{ github.sha }}

    - name: Extract zip file
      run: |
        docker create --name temp mod-builder:latest
        docker cp temp:/mod-release.zip ./FiveStack-${{ github.sha }}.zip
        docker rm temp

    - name: Sanitize branch name
      id: sanitize
      run: |
        BRANCH_NAME="${{ github.event.inputs.branch_name || github.ref_name }}"
        SANITIZED_BRANCH=$(echo "$BRANCH_NAME" | sed 's/[^a-zA-Z0-9]/-/g')
        echo "sanitized_branch=$SANITIZED_BRANCH" >> $GITHUB_OUTPUT
        
    - name: Build and Push Docker image
      uses: docker/build-push-action@v6
      with:
        push: true
        tags: |
            ghcr.io/${{ github.repository_owner }}/game-server:${{ steps.sanitize.outputs.sanitized_branch }}
            ghcr.io/${{ github.repository_owner }}/game-server:${{ github.sha }}
        build-args: |
          RELEASE_VERSION=${{ github.sha }}

    - name: Create Branch Release and Upload Asset
      uses: softprops/action-gh-release@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.sha }}
        name: Build ${{ github.sha }}
        draft: true
        prerelease: true
        files: |
          ./FiveStack-${{ github.sha }}.zip 