name: Tests

on:
  pull_request:
  push:
    branches:
      - "main"
      - "beta"

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        plugin: [counterstrikesharp, swiftly]
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "10.0.x"

      - name: Test
        run: dotnet test apps/${{ matrix.plugin }}/test/FiveStack.Tests.csproj -c Release
